version: "3"

services:
  web:
    image: nginx:1.15.12-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beejee_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwd
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf

  app:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
